### ISSUE TITLE
Matcher.group(String) is not available on Android 7.x or below

### ISSUE THREAD

**Issue by samlu** [ridencww/expression-evaluator#16]
I found matcher.group(String) will be used in Parser.tokenize().
Unfortunately, Matcher.group(String) is only available on Android 8.x+ so it won't work on Android 7.x or below.

**Comment by ridencww** [comment]
Thank you for pointing this out. I am out of town at present, but will look into issue as well as the others you posted when I return on 3/27. 

The tokenizer may be able to be refactored to map a capture group to an index (i.e., add a function to translate the name to an index) and then match.match(int) should work as it has been in the API prior to Java 7. I will investigate that when I return.

**Comment by samlu** [comment]
Thank you for your reply. I am currently using the following library which supports named group. FYI.
https://github.com/tony19/named-regexp

**Comment by ridencww** [comment]
I am still considering how to approach the solution. I would prefer not to require the named-regexp dependency for everyone. I have at least one consumer that is using this library because it doesn't require additional dependencies.  Still investigating.

**Comment by ridencww** [comment]
I can't see a way to cleanly integrate named-regexp for Android 7 and below and use the current code for more recent versions. I have users of this library that won't be able to the include named-regexp dependency in their code, so I can't just switch to using that library.

I think the best thing to do in this case is for those needing a version that works with Android 7.0 and below is to fork the library and replace the tokenize() method in Parser.java using the named-regexp version.
