### ISSUE TITLE
eval("SetGlobal('a', 123.45); aa=GetGlobal('a'); aa+1") does not work

### ISSUE THREAD

**Issue by samlu** [ridencww/expression-evaluator#17]
In Parser._GETGLOBAL(), it should change the following statement 
  value.set(globals.get(name == null ? "~nofind~" : name));
as 
  value.set(getGlobalVariable(name == null ? "~nofind~" : name));

for supporting the case insensitive case.

**Comment by ridencww** [comment]
Change pushed to develop pending final review.

**Comment by ridencww** [comment]
Issue corrected in release 2.3.0 and has been published to the Maven Central Repository (allow several hours to propagate).
